#!/bin/bash
#
# live install server - set static ip on eth0
#
# Internal settings
# -----------------
#
# IP address
IP_ADDR=192.168.0.1
#
# Subnet mask in CIDR notation
SUBNET_MASK_CIDR=/24

ip link set eth0 down
ip link set eth0 up

ip addr add ${IP_ADDR}$SUBNET_MASK_CIDR dev eth0
