#!/bin/bash
#
# live install server - environment setup script
#
#

# Settings
# --------
#
# environment settings file
ENV_CONF="./environment.conf"


# Functions
# ---------

function create_dir() {
    # create directory if it doesn't exist
    # $1: mountpoint
    if [ ! -d "$1" ]; then
        mkdir -p "$1"
        return $?
    else
        return 0
    fi
}

function makedirs() {
    # generate needed directories
    create_dir "$ARCHLIVE_TARGET_MNT" || return 1
    create_dir "$STORAGE_MNT" || return 1
    create_dir "$SFS_MNT" || return 1
    create_dir "$IMG_ROOT_MNT" || return 1
    create_dir "$IMG_HOME_MNT" || return 1
    create_dir "$LOCK_DIR" || return 1
    return 0
}

# (source the settings)
. "$ENV_CONF"

makedirs
